### ISSUE TITLE
 can't run on android version upper 12(using real devices) and on android version upper 11(using emulator)

### ISSUE THREAD

**Issue by zeinmuhammad25** [ashwithpoojary98/javaflutterfinder#13]
version depedency : 1.0.3
using appium version = appium@2.0.1

✔ Listing installed drivers
- uiautomator2@1.75.0 [installed (npm)]
- xcuitest@3.62.0 [installed (npm)]
- flutter@1.23.0 [installed (npm)]

command line:
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot determine the Dart Observatory URL after 10 retries. Original error: No observatory URL matching to '/(Observatory listening on |An Observatory debugger and profiler on\s.+\sis available at: |The Dart VM service is listening on )((http|\/\/)[a-zA-Z0-9:/=_\-.\[\]]+)/' was found in the device log

**Comment by ashwithpoojary98** [comment]
Hi @ashwithpoojary98  I hope you followed below steps before running the test cases
https://github.com/appium/appium-flutter-driver#usage-and-requirement

**Comment by zeinmuhammad25** [comment]
@ashwithpoojary98 I have done the steps suggested, to add enableFlutterDriverExtension in the main.dart class, but the problem is I can run it on the Samsung M12 device (OS 12), but it can't run on the Xiaomi Note 12 device (OS 13) and can't run in the entire emulator, after I updated to flutter@1.23.0

**Comment by ashwithpoojary98** [comment]
@ashwithpoojary98 might be a flutter issue.
Please add Appium logs

**Comment by zeinmuhammad25** [comment]
The problem I had was running the release version of the Flutter apk, so it couldn't run, after I used the debug version it could run again. thanks for the response
