### ISSUE TITLE
Is there a way to find "Native" elements by id/accessibilty_id using this finder?

### ISSUE THREAD

**Issue by hananmalka** [ashwithpoojary98/javaflutterfinder#4]

**Comment by ashwithpoojary98** [comment]
No, we can find elements using the normal Appium way
**driver.findElement(By.id(""));** like this

**Comment by hananmalka** [comment]
With this finder I'm getting: `locator strategy 'id' is not supported for this session flutter`
Using appium (java_client) 8.3.0

**Comment by ashwithpoojary98** [comment]
driver.switchContext("Native")

**Comment by hananmalka** [comment]
switchContext is not available for AppiumDriver in appium java_client version 8+

**Comment by ashwithpoojary98** [comment]
((SupportsContextSwitching)driver).context("Flutter");
try this

**Comment by ashwithpoojary98** [comment]
hope this issue got resolved, please reach out with any further issues.
